version: '3.11'

services:
  dash:
    command: tail -f /dev/null
    image: andromedapirate7777777/carpre:a2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80